# Generated by Django 4.0.10 on 2023-03-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='picture',
        ),
    ]
